services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes: 
      - ./backend:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-network

  php:
    build:
      context: './Docker'
    volumes:
      - ./backend:/var/www/html
    networks:
      - backend-network

  db:
    image: mysql:8.0
    container_name: mysql-database
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
