services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes: 
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-database
    ports:
      - "3307:3306"
    env_file:
      - ./backend/.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: './backend'
      dockerfile: 'Docker/Dockerfile'
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db-data:
