name: Run PHPUnit tests (docker)

on:
  pull_request:
    branches:
    - '**'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: install docker compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d php web

      - name: install composer dependencies
        run: |
          docker-compose exec -T php composer install

      - name: run PHPUnit tests
        run: docker-compose exec -T php vendor/bin/phpunit --testdox
    
      - name: stop docker containers
        run: docker-compose down
