name: Run PHPUnit tests (docker)

on:
  pull_request:
    branches:
    - '**'

jobs:
  phpunit:
    runs-on: ubuntu-lastest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: install docker compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
    
      - name: start docker containers
        run: docker-compose up -d --build

      - name: run PHPUnit tests
        run: docker-compose exec -T php vendor/bin/phpunit --testdox
    
      - name: stop docker containers
        run: docker-compose down